[package]
name = "texting_robots"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bstr = "0.2.17"
nom = "7.1.0"
regex = "1.5.4"